### PR TITLE
Rebind functions and objects after reloading

### PR DESCRIPTION
**Pull request by WanneSimon**
Rebind functions and object (bridge) after web page reloaded,  
etc: F5 pressed, `window.location.reload` .
Make development more convenient.

### CODE REVIEW

**Comment by WanneSimon** [comment]
Currently, all functions will be lost after page refresh.

**Comment by e3ndr** [comment]
There are a lot of changes made in this PR which don't really seem related.

**Comment by WanneSimon** [comment]
### rebind funtions:  
Fisrtly, defined `onloadScript` in `Webview` , it aims to invoke `__windowOnLoad` while  `onload` event is triggered.   
The `__windowOnLoad` is bound in constructor, it will rebind all functions.
 (Suddenly realizing that `onload` event will also trigger once during the first startup)

`functionHolder` holds all functions, the function will be saved while binding by `bind` .
`onloadHandler`, just a callback method for `onload` ( not important ). 

### rebind objects
Just a simple change in `BridgeScript.js`
``` js
if (window.Bridge) return
  ...
console.log("[Webview-Bridge]", "Injected bridge script.");
Bridge.__internal.sendMessageToJava("INIT", {});
// others appended by java
```
``` js
if (!window.Bridge) {
  ...
  console.log("[Webview-Bridge]", "Injected bridge script.");
  Bridge.__internal.sendMessageToJava("INIT", {});
}
// others appended by java
```

**Comment by e3ndr** [comment]
I credited you in the recent commit. Should be all fixed now :)

**Pull request closed without merging**
